#!/bin/bash 
UEFI_MODE=0
[ -d /sys/firmware/efi ] && UEFI_MODE=1
root_dev=$(findmnt -n -o SOURCE /mnt)
ROOT_UUID=$(blkid -s UUID -o value "$root_dev")
export ROOT_UUID
mnt_dev=$(findmnt -n -o SOURCE /mnt)
disk_dev=$(lsblk -no PKNAME "$mnt_dev")
DISK="/dev/$disk_dev"
echo "Диск, на котором лежит /mnt: $DISK"
if [ "$UEFI_MODE" -eq 1 ]; then
    function grub() {
        artix-chroot /mnt pacman -S grub os-prober efibootmgr --noconfirm
        artix-chroot /mnt grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=GRUB --removable --recheck
        artix-chroot /mnt sed -i 's/^GRUB_DISTRIBUTOR=.*/GRUB_DISTRIBUTOR="Quasar Linux"/' /etc/default/grub || echo 'GRUB_DISTRIBUTOR="Quasar Linux"' >> /etc/default/grub
        artix-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg
    }
    
    function efistub() {
        artix-chroot /mnt pacman -S efibootmgr os-prober --noconfirm
        artix-chroot /mnt efibootmgr -b 0000 -B
        artix-chroot /mnt cp /boot/vmlinuz-linux-zen /boot/efi/vmlinuz-linux-zen.efi
        artix-chroot /mnt cp /boot/initramfs-linux-zen.img /boot/efi/initramfs-linux-zen.img
        artix-chroot /mnt efibootmgr -c -d "$DISK" -p 1 -L "QuasarLinux" -l '\vmlinuz-linux-zen.efi' -u "root=UUID=$ROOT_UUID rw initrd=\initramfs-linux-zen.img"
    }
    function refind() {
        artix-chroot /mnt pacman -S efibootmgr os-prober refind --noconfirm
        artix-chroot /mnt refind-install
    }

    dialog --title "Выбор варианта" \
           --ok-label "Выбрать" \
           --no-cancel \
           --menu "Выберите опцию:" 15 40 4 \
           1 "grub" \
           2 "efistub" \
           3 "refind" 2>/tmp/bootloader.choice

    boot=$(cat /tmp/bootloader.choice)
    case $boot in
        1) grub ;;
        2) efistub ;;
        3) refind ;;
    esac
else
    function grub() {
        artix-chroot /mnt pacman -S grub os-prober --noconfirm
        artix-chroot /mnt grub-install --target=i386-pc --boot-directory=/boot --recheck "$DISK"
        artix-chroot /mnt sed -i 's/^GRUB_DISTRIBUTOR=.*/GRUB_DISTRIBUTOR="Quasar Linux"/' /etc/default/grub || echo 'GRUB_DISTRIBUTOR="Quasar Linux"' >> /etc/default/grub
        artix-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg
    }
    function syslinux() { 
        BOOT_NUMBER=$(echo $BOOT_PART | sed 's/.*[^0-9]\([0-9]\+\)$/\1/')
        parted $DISK set $BOOT_NUMBER boot on
        artix-chroot /mnt pacman -S syslinux --noconfirm
        mkdir -p /mnt/boot/syslinux
        artix-chroot /mnt extlinux --install /boot/syslinux
        cp /mnt/usr/lib/syslinux/bios/*.c32 /mnt/boot/syslinux/
        artix-chroot /mnt dd if=/usr/lib/syslinux/bios/mbr.bin of="$DISK" bs=440 count=1 conv=notrunc
        artix-chroot /mnt tee /boot/syslinux/syslinux.cfg << EOFD
DEFAULT Quasarlinux
PROMPT 0
TIMEOUT 50

LABEL Quasarlinux
    KERNEL /vmlinuz-linux-zen
    APPEND root=UUID=$ROOT_UUID rw
    INITRD /initramfs-linux-zen.img
EOFD
    }
    dialog --title "Выбор варианта" \
           --ok-label "Выбрать" \
           --no-cancel \
           --menu "Выберите опцию:" 15 40 4 \
           1 "grub" \
           2 "syslinux" 2>/tmp/bootloader.choice

    boot=$(cat /tmp/bootloader.choice) 
    case $boot in
        1) grub ;;
        2) syslinux ;;
    esac
fi
