#!/bin/bash
main () {
	parted() {
		clear
		echo "Выберите диск"
		lsblk -d -o NAME,SIZE,MODEL,TYPE
		read -p "Введите имя диска (например, sda/nvme0n1): " DISK
		DISK="/dev/$DISK"
		if [ ! -e "$DISK" ]; then
	  		echo "Ошибка: диск $DISK не существует!"
	        	exit 1
		fi
		cfdisk $DISK
		./parted "$DISK"
	}
	express() {
		parted
		./basepack
		./users
		./inst_pack
		./bootloader
		reboot
	}
	
	install() {
		./basepack
		main
	}
	users() {
		./users
		main
	}
	
	pack() {
		./inst_pack
		main
	}
	
	bootloader() {
		./bootloader
		main
	}
	seting=$(dialog --title "Quasar-instal" --menu "Выберите пункт: " 15 70 5 \
	1 "Разметка" \
	2 "Установка базы" \
	3 "Установка пакетов" \
	4 "Настройка пользователей" \
	5 "Установка загрузчика" 3>&1 1>&2 2>&3 3>&-)

	case $seting in
		1) parted ;;
		2) install ;;
		3) pack ;;
		4) users ;;
		5) bootloader ;;
	esac
}
main
