#!/bin/bash
set -euo pipefail
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
main() {
	clear
	echo "Выберите диск"
	lsblk -d -o NAME,SIZE,MODEL,TYPE
	read -p "Введите имя диска (например, sda/nvme0n1): " DISK
	DISK="/dev/$DISK"
	if [ ! -e "$DISK" ]; then
		echo "Ошибка: диск $DISK не существует!"
       	exit 1
	fi
	cfdisk $DISK
	$SCRIPT_DIR/parted "$DISK"
	$SCRIPT_DIR/basepack
	$SCRIPT_DIR/inst_pack
	$SCRIPT_DIR/users
	$SCRIPT_DIR/bootloader
	mkdir /mnt/install
	cp -r /installer/modules/post /mnt/install
	cp -r /installer/regions /mnt/install
}
parted_menu() {
    clear
	echo "Выберите диск"
	lsblk -d -o NAME,SIZE,MODEL,TYPE
	read -p "Введите имя диска (например, sda/nvme0n1): " DISK
	DISK="/dev/$DISK"
	if [ ! -e "$DISK" ]; then
		echo "Ошибка: диск $DISK не существует!"
       	exit 1
	fi
	cfdisk $DISK
}
user() {
	clear
	$SCRIPT_DIR/users
	clear
}

while true; do
    seting=$(dialog --title "Quasar-install" --menu "Выберите пункт:" 15 70 6 \
        1 "Экспресс" \
        2 "Разметка" \
        3 "Установка базы" \
        4 "Установка пакетов" \
        5 "Настройка пользователей" \
        6 "Установка загрузчика" \
        7 "Выход" \
        3>&1 1>&2 2>&3 3>&-)

    [ $? -ne 0 ] && break   # если жмём ESC/Cancel → выход

    case $seting in
        1) main ;;
        2) parted_menu ;;
        3) "$SCRIPT_DIR/basepack" ;;
        4) "$SCRIPT_DIR/inst_pack" ;;
        5) user ;;
        6) "$SCRIPT_DIR/bootloader" ;;
        7) break ;;
    esac
done
