#!/bin/bash
set -euo pipefail
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
main() {
	chmod +x $SCRIPT_DIR/parted_sh/*
	$SCRIPT_DIR/parted
	$SCRIPT_DIR/basepack
	$SCRIPT_DIR/inst_pack
	$SCRIPT_DIR/users
	$SCRIPT_DIR/bootloader
	mkdir /mnt/install
}
parted_menu() {
	chmod +x $SCRIPT_DIR/parted_sh/*
	$SCRIPT_DIR/parted
}
user() {
	clear
	$SCRIPT_DIR/users
	clear
}

while true; do
    if [ "${LENG_MODE:-}" = "ru" ]; then
        seting=$(dialog --title "Quasar-install" --menu "Выберите пункт:" 15 70 6 \
            1 "Экспресс" \
            2 "Разметка" \
            3 "Установка базы" \
            4 "Установка пакетов" \
            5 "Настройка пользователей" \
            6 "Установка загрузчика" \
            7 "Выход" \
            3>&1 1>&2 2>&3 3>&-)
    elif [ "${LENG_MODE:-}" = "eu" ]; then
        seting=$(dialog --title "Quasar-install" --menu "Select option:" 15 70 7 \
            1 "Express setup" \
            2 "Partitioning" \
            3 "Install base system" \
            4 "Install packages" \
            5 "User setup" \
            6 "Install bootloader" \
            7 "Exit" \
            3>&1 1>&2 2>&3 3>&-)
    fi
    [ $? -ne 0 ] && break   # если жмём ESC/Cancel → выход

    case $seting in
        1) main ;;
        2) parted_menu ;;
        3) "$SCRIPT_DIR/basepack" ;;
        4) "$SCRIPT_DIR/inst_pack" ;;
        5) user ;;
        6) "$SCRIPT_DIR/bootloader" ;;
        7) break ;;
    esac
done
