#!/bin/bash
set -euo pipefail
UEFI_MODE=0
[ -d /sys/firmware/efi ] && UEFI_MODE=1

DISK="$1"
echo "=== РАЗДЕЛЫ НА ДИСКЕ ==="
fdisk -l "$DISK" | grep "^/dev"
echo "======================="

# Выбор раздела под корень /
read -p "Введите раздел для ROOT (например, sda2): " ROOT_PART
ROOT_PART="/dev/$ROOT_PART"
lsblk -o NAME,SIZE,FSTYPE,MOUNTPOINT $DISK
if [ $UEFI_MODE -eq 1 ]; then
    read -p "Введите раздел для EFI (например, sda1): " BOOT_PART
    BOOT_PART="/dev/$BOOT_PART"
    mkfs.fat -F32 "$BOOT_PART"
else
    read -p "Введите раздел для BOOT (например, sda1): " BOOT_PART
    BOOT_PART="/dev/$BOOT_PART"
    mkfs.ext2 -f "$BOOT_PART"
fi

# Проверка разделов
[ ! -e "$ROOT_PART" ] && echo "Ошибка: $ROOT_PART не существует!" && exit 1
[ ! -e "$BOOT_PART" ] && echo "Ошибка: $BOOT_PART не существует!" && exit 1


format() {
	ext() {
		mkfs.ext4 -F "$ROOT_PART"
	}
	
	btrfs() {
		mkfs.btrfs -f "$ROOT_PART"
	}
	
	xfs() {
		mkfs.xfs -f -i size=512 "$ROOT_PART"
	}
	
	fs=$(dialog --title "Quasar-install" --menu "Выберите файловую систему: " 15 70 5 \
	1 "ext4" \
	2 "btrfs" \
	3 "xfs" 3>&1 1>&2 2>&3 3>&-)
	# Проверяем, не нажал ли пользователь Cancel или ESC
	if [ $? -ne 0 ]; then
	    echo "пропускаем"    
	fi

	case $fs in
		1) ext ;;
		2) btrfs ;;
		3) xfs ;;
	esac
	mount "$DISK" /mnt
	clear
}
lsblk
home_part() {
    read -p "Введите раздел для HOME (например, /dev/sda2): " HOME_PART
    [ ! -e "$HOME_PART" ] && echo "Ошибка: $HOME_PART не существует!" && exit 1

    format_home_ext() {
        mkfs.ext4 -F "$HOME_PART"
    }
    format_home_btrfs() {
        mkfs.btrfs -f "$HOME_PART"
    }
    format_home_xfs() {
        mkfs.xfs -f -i size=512 "$HOME_PART"
    }

    homefs=$(dialog --title "Выбор варианта" \
        --ok-label "Выбрать" \
        --no-cancel \
        --menu "Выберите файловую систему для /home" 15 40 4 \
        1 "ext4" \
        2 "btrfs" \
        3 "xfs" \
        3>&1 1>&2 2>&3 3>&-)

    clear
    case $homefs in
        1) format_home_ext ;;
        2) format_home_btrfs ;;
        3) format_home_xfs ;;
        *) echo "Неизвестный выбор" ;;
    esac
    mkdir /mnt/home
    mount "$HOME_PART" /mnt/home
}

non_home() {
    echo "OK"
}

home_parted=$(dialog --title "Выберите" --menu "Использовать отдельный раздел для /home:" 15 70 5 \
    1 "Отдельный раздел для /home" \
    2 "Без отдельных разделов" \
    3>&1 1>&2 2>&3 3>&-)

clear

if [ $? -ne 0 ]; then
    echo "пропускаем"
    exit 0
fi

case $home_parted in
    1) home_part ;;
    2) non_home ;;
    *) echo "Неизвестный выбор" ;;
esac


