#!/bin/bash

user_user() {
	user=$(dialog --inputbox "Введите имя пользователя" 8 40 3>&1 1>&2 2>&3 3>&-) 
	[ $? -ne 0 ] && clear && echo "Отменено" && exit 1
	clear
	fast-chroot /mnt useradd -m -g "$group" "$username"
	fast-chroot /mnt passwd $username
}
root_user() {
	echo "ведите пароль для root: "
	fast-chroot /mnt passwd

}
user_user
clear
root_user
