#!/bin/bash

full_post() {
	./post1_install
	./post2_install
	./android_install
	./audio_config
	./wine_install
	./android_install
	./clean_full
}

post() {
	./post1_install
}

post_two() {
	./post2_install
}

android_install() {
	./android_install
}

wine() {
	./wine_install
}

audio() {
	./audio_config
}

browser() {
	./browser_config
}

set=$(dialog --title "quasar-post-install" --menu "выберите пункт: " 15 70 5 \
1 "Экспрес" \
2 "1 этап" \
3 "2 этап" \
4 "Adroid установка" \
5 "Установка wine" \
6 "Установка аудио" \
7 "Установка браузера" \
3>&1 1>&2 2>&3 3>&-)


if [ $? -ne 0 ]; then
    clear
    echo "пропускаем"
fi

case $set in
	1) full_post ;;
	2) post ;;
	3) post_two ;;
	4) android_install ;;
	5) wine ;;
	6) audio ;;
	7) browser ;;
esac
