#!/bin/bash

DISK="$1"

ext() {
	mkfs.ext4 -F "$DISK"
}

btrfs() {
	mkfs.btrfs -f "$DISK"
}

xfs() {
	mkfs.xfs -f -i size=512 "$DISK"
}

fs=$(dialog --title "Quasar-install" --menu "Выберите файловую систему: " 15 70 5 \
1 "ext4" \
2 "btrfs" \
3 "xfs" 3>&1 1>&2 2>&3 3>&-)
# Проверяем, не нажал ли пользователь Cancel или ESC
if [ $? -ne 0 ]; then
    echo "пропускаем"    
fi

case $fs in
	1) ext ;;
	2) btrfs ;;
	3) xfs ;;
esac
mount "$DISK" /mnt
clear

home_part() {
    read -p "Введите раздел для HOME (например, sda2): " HOME_PART
    HOME_PART="/dev/$HOME_PART"
    [ ! -e "$HOME_PART" ] && echo "Ошибка: $HOME_PART не существует!" && exit 1

    format_home_ext() {
        mkfs.ext4 -F "$HOME_PART"
    }
    format_home_btrfs() {
        mkfs.btrfs -f "$HOME_PART"
    }
    format_home_xfs() {
        mkfs.xfs -f -i size=512 "$HOME_PART"
    }

    homefs=$(dialog --title "Выбор варианта" \
        --ok-label "Выбрать" \
        --no-cancel \
        --menu "Выберите файловую систему для /home" 15 40 4 \
        1 "ext4" \
        2 "btrfs" \
        3 "xfs" \
        3>&1 1>&2 2>&3 3>&-)

    clear
    case $homefs in
        1) format_home_ext ;;
        2) format_home_btrfs ;;
        3) format_home_xfs ;;
        *) echo "Неизвестный выбор" ;;
    esac
    mkdir /mnt/home
    mount "$HOME_PART" /mnt/home
}

non_home() {
    echo "OK"
}

home_parted=$(dialog --title "Выберите" --menu "Использовать отдельный раздел для /home:" 15 70 5 \
    1 "Отдельный раздел для /home" \
    2 "Без отдельных разделов" \
    3>&1 1>&2 2>&3 3>&-)

clear

if [ $? -ne 0 ]; then
    echo "пропускаем"
    exit 0
fi

case $home_parted in
    1) home_part ;;
    2) non_home ;;
    *) echo "Неизвестный выбор" ;;
esac


