#!/bin/bash 

waydroid() {
    sudo pacman -Syy
    sudo pacman -Suy
    sudo pacman -S lxc python python-gobject nftables dnsmasq gtk3 dbus-python --noconfirm
    yay -S waydroid-git
    yay -S waydroid-openrc
    sudo cat << 'EOF' > /etc/init.d/waydroid
#!/sbin/openrc-run
# Waydroid

description="Запуск Waydroid-контейнера"
command=/usr/bin/waydroid
command_args="container start"
pidfile=/run/waydroid.pid
command_background=false

depend() {
    need localmount
    use net
}
EOF
    sudo chmod +x /etc/init.d/waydroid
    sudo rc-update add waydroid default
    ls /dev/binder || echo "bider осудствует :("
    waydroid init


}

set=$(dialog --title "quasar-post-install" --menu "выберите пункт: " 15 70 5 \
    1 "Waydroid" \
    2 "BilisOS-QEMU/KVM" \
    3>&1 1>&2 2>&3 3>&-)
if [ $set -ne 0 ]; then
	echo "Установка прервана пользователем."
fi
case $set in
    1) waydroid ;;
    2) billisos_kvm ;;
