#!/bin/bash
set -euo pipefail
pipe() {
    ./audio_install pipewire
}

pulse() {
    ./audio_install pulseaudio
}

jack() {
    ./audio_install jack
}

audio=$(dialog --title "Меню" --menu "Выберите звуковой сервер: " 15 70 5 \
    1 "pulseaudio  (рекомендуется)" \
    3>&1 1>&2 2>&3 3>&-)

case $? in
    0)
        clear
        case $audio in
            2) pipe ;;
            1) pulse ;;
            3) jack ;;
            *) echo "Неверный выбор" ;;
        esac
        ;;
    *)
        clear
        echo "Ничего не выбрано или отмена."
        ;;
esac
