#!/bin/bash

main_menu() {
    full_post() {
        ./post1_install
        ./post2_install
        ./audio_config
        ./wine_install
        ./android_install
        ./clean_full
        read -p "Перезагрузить систему? (y/N): " reboot_choice
        if [[ $reboot_choice == "y" || $reboot_choice == "Y" ]]; then
            sudo reboot
        fi
    }

    post_one() {
        ./post1_install
    }

    post_two() {
        ./post2_install
    }

    android_install() {
        ./android_install
    }

    wine_install() {
        ./wine_install
    }

    audio_config() {
        ./audio_config
    }

    browser_install() {
        ./browser_install
    }

    clean_system() {
        ./clean_full
    }

    choice=$(dialog --title "quasar-post-install" --menu "Выберите пункт: " 15 70 8 \
        1 "Экспресс-установка (все этапы)" \
        2 "1 этап (базовые пакеты)" \
        3 "2 этап (DE/WM)" \
        4 "Android (Waydroid)" \
        5 "Wine" \
        6 "Аудио-система" \
        7 "Браузеры" \
        8 "Очистка системы" \
        3>&1 1>&2 2>&3 3>&-)

    case $? in
        0)
            case $choice in
                1) full_post ;;
                2) post_one ;;
                3) post_two ;;
                4) android_install ;;
                5) wine_install ;;
                6) audio_config ;;
                7) browser_install ;;
                8) clean_system ;;
            esac
            ;;
        *)
            clear
            echo "Выход из программы."
            exit 0
            ;;
    esac
    
    # Возврат в меню после выполнения
    read -p "Нажмите Enter для возврата в меню..."
    main_menu
}

main_menu
