#!/bin/bash 

sudo pacman -Syy

packages=(
    "go" on
    "qt5" on
    "qt6" on
    "ffmpeg" off
    "gamemode" off
    "polkit" off
    "x264" on
    "x265" on
    "openh264" on
    "qemu" off
    "grub-customizer" off
    "wayland" on
    "xorg" off
    "gtk2" off
    "gtk3" off
    "gtk4" on
    "qbittorrent" off
    "qbittorrent-openrc" off
)

# Создаем аргументы для dialog
dialog_args=()
for ((i=0; i<${#packages[@]}; i+=3)); do
    dialog_args+=("$((i/3+1))" "${packages[i]}" "${packages[i+1]}")
done

selected=$(dialog --checklist "Выберите нужные пакеты для установки:" 20 60 15 "${dialog_args[@]}" 3>&1 1>&2 2>&3 3>&-)

case $? in
    0)
        clear
        if [ -n "$selected" ]; then
            install_list=()
            for num in $selected; do
                index=$(( (num - 1) * 3 ))
                install_list+=("${packages[index]}")
            done
            
            echo "Устанавливаем: ${install_list[@]}"
            sudo pacman -S --noconfirm "${install_list[@]}"
        else
            echo "Не выбрано ни одного пакета."
        fi
        ;;
    *)
        clear
        echo "Выбор пакетов отменен."
        ;;
esac
