#!/bin/bash
wine() {
    sudo pacman -S wine winetricks  --noconfirm
}

staging() {
    sudo pacman -S wine-staging winetricks  --noconfirm
}

quasar() {
    sudo pacman -S wine-staging winetricks gamemode --noconfirm
    wineboot --init
    sleep 2
    clear
    winetricks --force -q --unattended corefonts tahoma cjkfonts vcrun6 vcrun2003 vcrun2005 vcrun2008 vcrun2010 vcrun2012 vcrun2013 vcrun2015 vcrun2019 vcrun2022 dotnet20 dotnet30 dotnet35 dotnet40 dotnet45 dotnet462 dotnet48 dotnetcoredesktop3 dotnetcoredesktop6 d3dcompiler_43 
    winetricks --force -q --unattended d3dcompiler_47 d3dx9 d3dx10 d3dx11_43 directx9 directx10 directx11 xact xinput quartz devenum wmp9 wmp10 wmp11 msxml3 msxml4 msxml6 gdiplus riched20
    winetricks --force -q --unattended riched30 vb6run mfc40 mfc42 mfc70 mfc80 mfc90 mfc100 mfc110 mfc140 ie8 flash silverlight physx openal dsound xna40 faudio dxvk vkd3d dgvoodoo2 win10
    sleep 5
    clear
}

ge() {
    wget -P /tmp https://github.com/GloriousEggroll/wine-ge-custom/releases/download/GE-Proton8-26/wine-lutris-GE-Proton8-26-x86_64.tar.xz
    sleep 1
    tar -xf /tmp/wine-lutris-GE-Proton8-26-x86_64.tar.xz -C ~/.apps
    sleep 1
    cd ~/.apps
    mv lutris-GE-Proton8-26-x86_64 wine-ge
    export PATH="$HOME/.apps/wine-ge/bin:$PATH"
    export XDG_DATA_DIRS="$HOME/.apps/wine-ge/share:$XDG_DATA_DIRS"
    sleep 1 
    wineboot --init
}

proton() {
    wget -P /tmp https://github.com/GloriousEggroll/proton-ge-custom/releases/download/GE-Proton10-13/GE-Proton10-13.tar.gz
    tar -xf /tmp/GE-Proton10-13.tar.gz -C ~/.apps
    mv GE-Proton10-13 proton-ge
    sudo ln -sf proton-ge/files/bin/* /usr/local/bin
    sudo ln -sf proton-ge/files/share/* /usr/local/share
}

port() {
    yay -S protoroton
}

dialog --title "Меню" --menu "Выберите нужный wine: " 15 70 5 \
1 "Wine" \
2 "Wine-staging" \
3 "Wine-staging с DXVK/VKD3D" \
4 "Wine-ge" \
5 "Proton-ge" \
6 "PortProton" 2>/tmp/wine.txt
if [ $? -ne 0 ]; then
    clear
    echo "пропускаем"
    rm -f /tmp/wine.txt    
fi
$chice=$(cat /tmp/wine.txt)
case $choice in
    1) wine ;;
    2) staging ;;
    3) quasar ;;
    4) ge ;;
    5) proton ;;
    7) port ;;
    6) no ;;
    *) echo "Неверный выбор" ;;
esac
rm -f /tmp/wine.txt 
clear

