#!/bin/bash
wm="$1"

install_hyprland() {
    sudo pacman -S --needed hyprland waybar rofi kitty hyprland-protocols hyprgraphics hypridle hyprcursor hyprland-qt-support hyprutils xdg-desktop-portal-hyprland wayland seatd --noconfirm
    sudo pacman -S --needed --noconfirm dolphin 
}

install_sway() {
    sudo pacman -S sway --noconfirm
    sudo pacman -S swayidle swaylock waybar wl-clipboard foot wayland seatd --noconfirm
    sudo pacman -S --needed --noconfirm dolphin
}

install_i3() {
    sudo pacman -S xorg-server xorg-xinit --noconfirm --needed
    sudo pacman -S --needed --noconfirm i3-wm i3status i3lock dmenu rxvt-unicode foot
    sudo pacman -S --needed --noconfirm dolphin
}

# Установка ly для всех WM
sudo pacman -S ly ly-openrc --noconfirm
sudo rc-update add ly default

case "$wm" in
    hyprland) install_hyprland ;;
    sway) install_sway ;;
    i3wm) install_i3 ;;
    *) echo "Неизвестный оконный менеджер: $wm" ;;
esac
