#!/bin/bash
wm="$1"

install_hyprland() {
    sudo pacman -S --needed hyprland waybar rofi kitty hyprland-protocols hyprgraphics hypridle hyprcursor hyprland-qt-support hyprutils xdg-desktop-portal-hyprland --noconfirm
    sudo pacman -S --needed --noconfirm dolphin 
    sudo rc-update add ly default
}

install_sway() {
    sudo pacman -S sway swayidle swaylock waybar wl-clipboard foot wayland seatd seatd-openrc --needed --noconfirm
    sudo chmod +x /etc/init.d/seatd
    sudo rc-update add seatd default
}

install_i3() {
    sudo pacman -S xorg-server xorg-xinit --noconfirm --needed
    sudo pacman -S --needed --noconfirm i3-wm i3status i3lock dmenu rxvt-unicode
}

# Установка ly для всех WM
sudo pacman -S ly ly-openrc --noconfirm
sudo rc-update add ly default

case "$wm" in
    hyprland) install_hyprland ;;
    sway) install_sway ;;
    i3wm) install_i3 ;;
    *) echo "Неизвестный оконный менеджер: $wm" ;;
esac
